netlify/blobs

- src/server.test.ts
- src/server.ts
Adds an optional `onRequest` callback to `BlobsServer` that is fired on every request. We'll use this in the CLI for https://github.com/netlify/pillar-runtime/issues/780.
> feat: add `onRequest` callback to server

- src/server.test.ts
- src/server.ts
Closes https://linear.app/netlify/issue/COM-192/blob-server-doesnt-work-on-windows-for-deploy-stores.
> fix: handle deploy-scoped stores on Windows

- src/server.ts
Some users are seeing this error:
```
[Netlify Blobs server] Error when writing data: [Error: EXDEV: cross-device link not permitted, rename '/tmp/netlify-blobsLCv61H/entries/7a7c9eec-3514-426a-bea9-3f7e7f659808/... -> '/run/media/.../site/.netlify/blobs-serves/entries/7a7c9eec-3514-426a-bea9-3f7e7f659808/...'] {
errno: -18,
code: 'EXDEV',
syscall: 'rename',
path: 'redacted',
dest: 'redacted'
}
```
According to https://stackoverflow.com/questions/43206198/what-does-the-exdev-cross-device-link-not-permitted-error-mean, this happens when a file is renamed across two different partitions of a disk, which can definitely happen on dev machines we don't have control over. It mentions that a good fix is to copy & remove instead - that's what this PR does.
Resolves …
> fix: copy temp file to prevent `EXDEV: cross-device link not permitted`

- README.md
- src/environment.ts
- src/lambda_compat.test.ts
- src/lambda_compat.ts
- src/types.ts
Adds a `connectLambda()` method that makes it easy for functions using the Lambda compatibility mode to interact with Netlify Blobs.
More information, including example usage, in the README.
Part of https://linear.app/netlify/issue/FRA-177/nextjs-support-blobs-getstore-in-runtime-generated-functions.
> feat: add `connectLambda` method

- src/server.ts
We've seen some intermittent failures when handling `set()` calls in the Blobs server, where we seem to write a zero-bytes file to the final location.
This PR attempts to solve that by simplifying the logic for handling the streaming of these requests, replacing `pipe()` with the better `pipeline()`.
> fix: simplify streaming of server writes

- src/client.ts
- src/consistency.ts
- src/environment.ts
- src/main.test.ts
- src/store.ts
Adds a `consistency` property to both the store constructors and the `get*` methods.
**List other issues or pull requests related to this problem**
ref COM-310
ref FRA-238
> feat: add `consistency` configuration property

- .eslintrc.cjs
- src/backend/list_stores.ts
- src/client.ts
- src/consistency.test.ts
- src/lambda_compat.test.ts
- src/list.test.ts
- src/main.test.ts
- src/main.ts
- src/store.ts
- src/store_list.test.ts
- src/store_list.ts
Adds a `listStores` method for listing site-scoped stores.
Please note that the internal logic for namespacing stores has changed, which means that any site-level stores that have been created using a previous version of the Netlify Blobs client will not be available in the new version. You can continue to use those stores with the previous client, but the data will not be accessible once you upgrade.
**List other issues or pull requests related to this problem**
Closes COM-454.
> feat!: add `listStores` method

- src/client.ts
- src/main.test.ts
- src/server.ts
- src/store.ts
Allows site-scoped stores using the legacy namespace to be access using a special prefix. This is not a customer-facing feature and is meant to be used by Netlify tooling.
**List other issues or pull requests related to this problem**
Part of ADN-370.
> feat: allow internal access to legacy stores

- src/client.ts
- src/server.test.ts
- src/server.ts
This is a follow-up to #147. The new API endpoints can respond to a "get blob" operation by issuing a signed URL or by returning the blob bytes directly. This behaviour is controlled with the `accept` header.
This PR ports that behaviour to the local server.
> feat: respect `accept` header in server

- src/environment.ts
- src/lambda_compat.ts
- src/metadata.ts
- src/retry.ts
- src/store.ts
- src/util.ts
Replaces any Node built-in modules with cross-runtime equivalents.
The exception is the local server, which is Node only.
> feat: remove usage of Node built-ins

- build.mjs
- package.json
- server.d.ts
- src/main.ts
Moves the local server to a sub-module export. This means that the way the `BlobsServer` class is imported has changed:
```diff
-import { BlobsServer } from "@netlify/blobs"
+import { BlobsServer } from "@netlify/blobs/server"
const server = new BlobsServer()
```
> feat!: move server to sub-module export

- src/main.ts
The NPM package doesn't include the `connectLambda` function causing an error like:
```
✘ [ERROR] No matching export in "node_modules/@netlify/blobs/dist/main.js" for import "connectLambda"
netlify/functions/api.ts:4:8:
4 │ import {connectLambda} from '@netlify/blobs'
```
This PR exports that function so it should exist in the package.
> fix: include connectLambda in dist

- src/client.ts
- src/environment.ts
- src/main.test.ts
- src/store_factory.ts
Adds experimental support for region selection in Netlify Blobs. Right now, this is limited to deploy-scoped stores and is configured using a new `experimentalRegion` parameter of `getDeployStore`. It can be used as follows:
- If `experimentalRegion` is set to `auto`, it instructs the backend to automatically pick the region that is configured for the deploy
- This is only supported in our API endpoints, so it's not available when initialising the store with a `edgeURL` property
- If `experimentalRegion` is set to `context`, it tries to load the name of the region from the environment context, throwing an error if not found
- If `experimentalRegion` is unset (or set to anything else), the existing behaviour will be observed
Part of COM-585.
> feat: add experimental support for region selection

- src/main.test.ts
- src/main.ts
Exports the `setEnvironmentContext()` method, which consumers like Netlify Build can use to populate the Blobs context.
> feat: export `setEnvironmentContext()`

- src/server.test.ts
- src/server.ts
Exposes a `url` property to the local server's `onRequest` callback, containing the URL of the incoming request.
> feat: add `url` to server's `onRequest` callback

- src/server.test.ts
- src/server.ts
When using the new `experimentalRegion` property in a deploy-scoped store in conjunction with `edgeURL`, the client will send the region in the URL path with a `region:` prefix. This PR makes the local server understand that and point requests to the right path on disk.
> feat: handle `region:` prefix in local server

- src/client.ts
- src/headers.ts
- src/main.test.ts
- src/store.ts
- src/util.ts
Adds the request ID, if found, to any error messages we log. This makes it easier for the Netlify team to troubleshoot when a user reports a problem.
> feat: add request ID to error messages

- src/headers.ts
- src/main.test.ts
- src/server.test.ts
- src/util.ts
Follow-up to #165, adding the contents of the `x-nf-error` header we get from the edge endpoints.
> feat: add details to error message

- src/main.test.ts
- src/store.ts
- src/store_factory.ts
Part of https://linear.app/netlify/issue/ADN-97/extend-getdeploystore-to-accept-a-name.
> feat: support named deploy-scoped stores

- src/client.ts
- src/consistency.test.ts
- src/main.test.ts
- src/region.ts
- src/server.test.ts
- src/store_factory.ts
In #158, we've added experimental support for configurable regions to deploy-scoped stores (i.e. stores created with `getDeployStore()`). It works as follows:
- For API calls (i.e. when using an API token), you can use `getDeployStore({ experimentalRegion: "auto" })` to instruct the API to choose the same region as the one configured for functions
- If this parameter is not supplied, the Blobs client will not send any region parameter to the API, which means the default region will be used
- For edge calls (i.e. when using a token from a serverless function or an edge function), you can use `getDeployStore({ experimentalRegion: "context" })` to instruct the CDN to choose the region defined in the environment
- If a region is not defined in …
> feat!: add region parameter

- src/list.test.ts
- src/store.ts
- src/store_list.test.ts
- src/store_list.ts
Fixes issue described in: https://linear.app/netlify/issue/FRP-1224/blobs-list-throws-json-parse-error-on-404-paths
fixes error throws for 404ing content on listing functions. This updates store listing and content listing.
> fix: 404ing list results should return empty iterators, not throw

- src/region.ts
🎉 Thanks for sending this pull request! 🎉
Fixes
```
InvalidBlobsRegionError: ap-southeast-2 is not a supported Netlify Blobs region. Supported values are: us-east-1, us-east-2.
```
kind of errors. We do have support for that (and some other regions) and forcing those specific regions was failing options validation.
With this change attempting to use region not from the list also print updated "Supported values":
```
InvalidBlobsRegionError: ap-southeast-3 is not a supported Netlify Blobs region. Supported values are: us-east-1, us-east-2, eu-central-1, ap-southeast-1, ap-southeast-2
```
> fix: add missing eu-central-1, ap-southeast-1 and ap-southeast-2 regions
